server:
  port: 8080

spring:
  profiles:
    active: @activatedProperties@

cloud:
  aws:
    credentials:
      access-key: <ask vincent for key>
      secret-key: <ask vincent for key>
    region:
      static: ap-southeast-2
      auto: false
    end-point:
      service: https://sqs.ap-southeast-2.amazonaws.com
      buyer:
        uri: https://sqs.ap-southeast-2.amazonaws.com/099209825265/order_matching_buyer_queue.fifo
      seller:
        uri: https://sqs.ap-southeast-2.amazonaws.com/099209825265/order_matching_seller_queue.fifo

bs:
  sql:
    driver: org.postgresql.Driver
    url: <dummy url>
    username: omnitrade
    password: omnitrade
    pool:
      name: omnitrade-orders

management:
  endpoints:
    web:
      exposure:
        include: "*"

keycloak:
  auth-server-url: https://oauth.omni-trade.xyz:8180
  principal-attribute: preferred_username
  realm: IamOrderMatching
  public-client: 'true'
  resource: iam-ordermatching

logging:
  level:
    org:
      springframework:
        security: DEBUG
