server:
  port: 8880

cloud:
  aws:
    credentials:
      access-key: x
      secret-key: x
    region:
      static: ap-southeast-2
      auto: false
    end-point:
      service: http://elasticmq:9324/
      buyer:
        uri: http://elasticmq:9324/000000000000/order_matching_buyer_queue.fifo
      seller:
        uri: http://elasticmq:9324/000000000000/order_matching_seller_queue.fifo

bs:
  sql:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/omnitrade_orders?characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: omnitrade
    password: omnitrade
    pool:
      name: omnitrade-orders

management:
  endpoints:
    web:
      exposure:
        include: "*"

keycloak:
  auth-server-url: https://oauth.omni-trade.xyz:8180
  principal-attribute: preferred_username
  realm: IamOrderMatching
  public-client: 'true'
  resource: iam-ordermatching
