name: Deploy Frontend to Production
on:
  push:
    branches:
      - production/frontend

env:
  DEPLOY_DIRECTORY: /var/www/swe5005/deploy/frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd front-end
          npm install
      - name: Generate build
        run: |
          cd front-end
          npm run build
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: production-deploy
          path: front-end/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: production-deploy
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PRODUCTION_REVERSE_PROXY_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: |
          ssh ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_REVERSE_PROXY_HOST }} \
          " \
            sudo mkdir -p $DEPLOY_DIRECTORY && \
            sudo chown -R 1001:1001 $DEPLOY_DIRECTORY && \
            sudo chmod 775 -R $DEPLOY_DIRECTORY && \
            sudo mkdir -p $DEPLOY_DIRECTORY/backup/frontend/${{ github.sha }} \
          "
          rsync -avzb --backup-dir=$DEPLOY_DIRECTORY/backup/frontend/${{ github.sha }} --delete ./ ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_REVERSE_PROXY_HOST }}:$DEPLOY_DIRECTORY
      - name: Timestamping deployment
        run: |
          ssh ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_REVERSE_PROXY_HOST }} \
          " \
            cd $DEPLOY_DIRECTORY && \
            echo "Commit ${{ github.sha }} deployed at $(TZ=":Asia/Singapore" date)" > deployment_info.txt \
          "
