name: Deploy Backend to Production
on:
  push:
    branches:
      - production/backend
      - devops/test

env:
  DEPLOY_DIRECTORY: /var/www/swe5005

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PRODUCTION_APP_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          ssh ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_APP_HOST }} \
          " \
            cd $DEPLOY_DIRECTORY && \
            docker compose up -d
          "
          ssh ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_APP_HOST }} \
          " \
            cd $DEPLOY_DIRECTORY && \
            mv docker-compose.yml docker-compose.yml.backup \
            mv back-end/project-capstone/03-nus-order-matching-service/03-order-matching-service/src/main/resources/application-docker.yml application-docker.yml.backup
          "
          rsync -avzb ./ ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_APP_HOST }}:$DEPLOY_DIRECTORY
          ssh ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_APP_HOST }} \
          " \
            cd $DEPLOY_DIRECTORY && \
            mv docker-compose.yml.backup docker-compose.yml \
            mv application-docker.yml.backup back-end/project-capstone/03-nus-order-matching-service/03-order-matching-service/src/main/resources/application-docker.yml
          "
          ssh ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_APP_HOST }} \
          " \
            cd $DEPLOY_DIRECTORY && \
            docker compose up -d
          "

      - name: Timestamping deployment
        run: |
          ssh ${{ secrets.PRODUCTION_SSH_USERNAME }}@${{ secrets.PRODUCTION_APP_HOST }} \
          " \
            cd $DEPLOY_DIRECTORY && \
            echo "Commit ${{ github.sha }} deployed at $(TZ=":Asia/Singapore" date)" > deployment_info.txt \
          "
